---
title: "Task 4"
author: "Yvonne Dinh"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(broom)
library(tibble)
library(lubridate)
library(here)
library(janitor)
library(kableExtra)
library(ggbeeswarm)
library(effsize)
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
#read in data
mono=read.csv(here("data","mono_lake_annual_levels.csv"), skip=5) %>% 
  clean_names()

#create a data viz
ggplot(mono, aes(x=year, y=lake_level_feet_above_sea_level))+
  labs(x="Year",y="Lake Level, feet above sea level", title="Levels at Mono Lake (1850-2017)")+
  geom_line(color="skyblue3")+
  theme_minimal()+
  coord_cartesian(ylim=c(6340, 6430)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 9))+
  geom_segment(aes(x=1849, xend=2018, y=6350, yend=6350), color="indianred4")+
  geom_segment(aes(x=1849, xend=2018, y=6360, yend=6360), color="indianred3")+
  geom_segment(aes(x=1849, xend=2018, y=6377, yend=6377), color="indianred1")+
  geom_area(fill="lightskyblue", alpha=0.3)+
  annotate(geom = "point", x = 1941, y = 6417, shape = 19, size = 1, color = "violetred2")+ #LA DWP began diverting water from Mono Lake to LA
  annotate(geom = "point", x = 1978, y = 6375, shape = 19, size = 1, color = "violetred2")+ #The Mono Lake Committee was founded
  geom_label(label="1941: LADWP begins diverting water from Mono Lake to LA", x=1971.5, y=6420.5, size = 2)+
  geom_label(label="1978: The Mono Lake Committee was founded", x=2001, y=6371, size = 2) +
  geom_label(label="6377 ft: Land bridges emerge", x=1867, y=6380, size = 2) +
  geom_label(label="6360 ft: Availability of brine shrimp and brine flies begin to decrease", x=1886, y=6363, size = 2)+
  geom_label(label="6350 ft: Availability of brine shrimp and brine flies become acutely low", x=1887, y=6353, size = 2)
```

Figure 1. Lake Levels, in feet above sea level at Mono Lake from 1850 - 2017. Horizontal lines show critical lake levels and points show important events that occurred. 
